include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/Container-Scanning.gitlab-ci.yml

stages:
  - test
  - deploy

# Cache pip dependencies to speed up subsequent builds
cache:
  paths:
    - .cache/pip

# Security testing stage
sast:
  stage: test

secret_detection:
  stage: test

dependency_scanning:
  stage: test

container_scanning:
  stage: test

# Documentation deployment stage
pages:
  stage: deploy
  image: python:3.8-slim
  script:
    - rm -rf public
    - pip install -r requirements.txt
    - mkdocs build --verbose
  artifacts:
    paths:
      - public
  only:
    - main
    - tags

# Notification stage (optional)
# Add a notification stage for failed builds
failure_notification:
  stage: deploy
  script:
    - echo "Build failed. Notifying team."
  when: on_failure
